export const QUALITY_PRESETS = Object.freeze({
  low: Object.freeze({
    maxDevicePixelRatio: 1,
    ambientDotSpacing: 380,
    glowEnabled: false,
    gridEnabled: true,
    targetFoodCount: 500,
    targetBotCount: 8,
    collectionParticleMultiplier: 0.55,
    boostParticleMultiplier: 0.55,
    botParticleMultiplier: 0.40,
    speedLineCount: 9,
  }),
  medium: Object.freeze({
    maxDevicePixelRatio: 1.5,
    ambientDotSpacing: 290,
    glowEnabled: true,
    gridEnabled: true,
    targetFoodCount: 900,
    targetBotCount: 14,
    collectionParticleMultiplier: 0.8,
    boostParticleMultiplier: 0.78,
    botParticleMultiplier: 0.65,
    speedLineCount: 16,
  }),
  high: Object.freeze({
    maxDevicePixelRatio: 2,
    ambientDotSpacing: 225,
    glowEnabled: true,
    gridEnabled: true,
    targetFoodCount: 1450,
    targetBotCount: 22,
    collectionParticleMultiplier: 1,
    boostParticleMultiplier: 1,
    botParticleMultiplier: 0.85,
    speedLineCount: 25,
  }),
});

export const GRAPHICS_CONFIG = Object.freeze({
  defaultQuality: "auto",
  autoQualityFallback: "medium",
  worldGridSize: 90,
  minZoom: 0.60,
  maxZoom: 0.96,
  mobileZoomMultiplier: 0.68,
  mobileMinimumZoom: 0.42,
  cameraFollowSpeed: 7,
  zoomFollowSpeed: 4,
  arenaFill: "#0a1728",
  arenaBorder: "#43d8ff",
});
